# This file contains values from Cookiecutter

default_context:
  project_name: "yarc"
  project_description: "YARC - DSL for Synthetic Data Generation"
  organization: "yarc"
  license: "MIT"
  minimal_python_version: 3.10
  github_name: "fcarne"
  email: "federico.carne@hotmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
